/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Archive: typeof import('./.vitepress/theme/components/Archive.vue')['default']
    Copyright: typeof import('./.vitepress/theme/components/layout/Copyright.vue')['default']
    Footer: typeof import('./.vitepress/theme/components/layout/Footer.vue')['default']
    Tag: typeof import('./.vitepress/theme/components/Tag.vue')['default']
    WordCloud: typeof import('./.vitepress/theme/components/WordCloud.vue')['default']
  }
}
